service:
  name: account-sync

package:
  individually: false
  exclude:
    - node_modules/**

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

resources: ${file(serverless/resources.yaml)}

provider: 
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  memorySize: 512
  timeout: 30
  environment: 
    tableName: ${self:custom.db.accsynctablename}
  variableSyntax: "\\${((?!AWS|SecretName)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)\\*\\?]+?)}"

functions:
  SignUp:
   handler: src/lambdas/signUp.handler
   events:
    - http:
        path: signUp/
        method: post
        cors: true

  FirstLambda:
   handler: src/lambdas/first.handler
   events:
     - http:
         path: first/
         method: get
         cors: true
         authorizer: ${self:custom.authorizer}      

  SecondLambda:       
   handler: src/lambdas/second.handler
   events:
     - http:
         path: second/
         method: post
         cors: true
         authorizer: ${self:custom.authorizer}

custom: 
  stage: ${opt:stage, env:STAGE}
  region: ${opt:region, 'ap-southeast-2'}
  db: 
    accsynctablename: users_table
  authorizer: 
    type: COGNITO_USER_POOLS
    authorizerId:
      Ref: ApiGatewayAuthorizer
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: false

        