service:
  name: account-sync

package:
  individually: false
  exclude:
    - node_modules/**

plugins:
  - serverless-dotenv-plugin
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-iam-roles-per-function
 
resources: ${file(serverless/resources.yaml)}

provider: 
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:* 
      Resource: 
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - ${self:custom.region}
            - !Ref AWS::AccountId
            - table/${self:custom.db.accsynctablename}
    - Effect: Allow
      Action: 
        - dynamodb:* 
      Resource: 
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - ${self:custom.region}
            - !Ref AWS::AccountId
            - table/${self:custom.db.clientstablename}
    - Effect: Allow
      Action: 
        - dynamodb:* 
      Resource: 
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - ${self:custom.region}
            - !Ref AWS::AccountId
            - table/${self:custom.db.reportstablename}
    - Effect: Allow
      Action: 
        - dynamodb:* 
      Resource: 
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - ${self:custom.region}
            - !Ref AWS::AccountId
            - table/${self:custom.db.taxcodestablename}                             
    - Effect: Allow
      Action:
        - appsync:GraphQL
      Resource: 
        - Fn::Join:
            - '/'
            - - !Ref GraphQlApi
              - '*'
    - Effect: Allow 
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ''
          - - "arn:aws:s3:::"
            - !Ref S3Bucket
            - "/*"                                

  environment: 
    usersTable: ${self:custom.db.accsynctablename}
    clientsTable: ${self:custom.db.clientstablename}
    reportsTable: ${self:custom.db.reportstablename}
    clientSecret: ${self:custom.clientsecret}
    clientId: ${self:custom.clientid}
    environment: ${self:custom.env}
    redirectUri: ${self:custom.redirecturi}
    intuitAPI: ${self:custom.intuituri}
    reportBucket: ${self:custom.reportBucketName}
    bucketLink: ${self:custom.bucketLink}
  variableSyntax: "\\${((?!AWS|SecretName)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)\\*\\?]+?)}"

functions:
  UploadReportToS3:
    handler: src/lambdas/uploadToS3.handler
    events:
      - http:
          path: download/{id}
          method: get
          cors: true
          authorizer: ${self:custom.authorizer}
  SignUp:
   handler: src/lambdas/signUp.handler
   events:
    - http:
        path: signUp/
        method: post
        cors: true
        authorizer: ${self:custom.authorizer}

  RefreshTokens:
    handler: src/lambdas/refreshToken.handler
    events:
      - schedule: rate(1 hour)
   
  GetReportFromIntuit:
    handler: src/lambdas/storeReportToDb.handler
    events:
      - http:
          path: report-settings/{realmId}
          method: post
          cors: true
          authorizer: ${self:custom.authorizer}    

  StoreIntuitTokens:
   handler: src/lambdas/storeTokens.handler
   events:
     - http:
         path: tokens/
         method: post
         cors: true
         authorizer: ${self:custom.authorizer}

  IntuitSignInRedirect:       
   handler: src/lambdas/intuitSignInRedirect.handler
   events:
     - http:
         path: intuitSignIn/
         method: get
         cors: true
         authorizer: ${self:custom.authorizer}

custom: 
  stage: ${opt:stage, env:STAGE}
  region: ${opt:region, 'ap-southeast-2'}
  db: 
    accsynctablename: users_table
    clientstablename: clients_table
    reportstablename: reports_table
    taxcodestablename: taxcodes_table
  clientsecret: ${env:CLIENT_SECRET}
  clientid: ${env:CLIENT_ID}
  env: ${env:ENVIRONMENT}
  redirecturi: ${env:REDIRECT_URI}
  intuituri: ${env:INTUIT_API_URI}
  reportBucketName: ${env:REPORT_BUCKET_NAME}
  bucketLink: ${env:BUCKET_LINK}
  authorizer: 
    type: COGNITO_USER_POOLS
    authorizerId:
      Ref: ApiGatewayAuthorizer
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: true
    packager: npm
  appSync:
    name: ${self:service.name}
    authenticationType: API_KEY
    # userPoolConfig:
    #    awsRegion: ${self:custom.region}
    #    userPoolId: !Ref CognitoUserPool
    #    defaultAction: "ALLOW"
    mappingTemplates:
      - dataSource: Clients
        type: Query
        field: getClients
        request: 'scanClient-request-mapping-template.vtl'
        response: 'taxCodes-response-mapping-template.vtl'  
      - dataSource: Reports
        type: Query
        field: getReport
        request: 'getReport-request-mapping-template.vtl'
        response: 'common-response-mapping-template.vtl'
      - dataSource: Clients
        type: Query
        field: getClient
        request: 'getReport-request-mapping-template.vtl'
        response: 'common-response-mapping-template.vtl'
      - dataSource: TaxCodes
        type: Query
        field: getTaxCodes
        request: 'scanTaxCodes-request-mapping-template.vtl'
        response: 'taxCodes-response-mapping-template.vtl'   
      - dataSource: Reports
        type: Mutation
        field: updateReport
        request: 'updateReport-request-mapping-template.vtl'
        response: 'common-response-mapping-template.vtl'
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Clients
        description: Clients table
        config:
          tableName: ${self:custom.db.clientstablename}
          # serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
      - type: AMAZON_DYNAMODB
        name: Reports
        description: Reports table
        config:
          tableName: ${self:custom.db.reportstablename}
          # serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
      - type: AMAZON_DYNAMODB
        name: TaxCodes
        description: Tax codes table
        config:
          tableName: ${self:custom.db.taxcodestablename}            
